name: 'Internal App Sharing'
description: 'Upload aab/apk to Internal App Sharing on Play Console'
inputs:
  serviceAccountJsonPlainText:
    description: 'The service account json plain text private key file to authorize the upload request'
    required: true 
  packageName:
    description: 'Package name of the application'
    required: true
  apkFilePath:
    description: '.apk file path'
    required: false
  aabFilePath:
    description: '.aab file path'
    required: false
outputs:
  downloadUrl:
    description: 'The download URL generated for the uploaded artifact.'
  certificateFingerprint:
    description: 'The SHA256 fingerprint of the certificate used to signed the generated artifact.'
  sha256:
    description: 'The SHA-256 hash of the artifact represented as a lowercase hexadecimal number, matching the output of the sha256sum command.'       
runs:
  using: 'node12'
  main: 'lib/index.js'